dist: bionic

language: python
python:
  - "3.8"

addons:
  chrome: latest

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# database to use
env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - install webdriver-manager

# command to run tests
script:
  - python manage.py test