dist: bionic

language: python
python:
  - "3.8"

addons:
  chrome: stable

# command to install dependencies
install:
  - pip install -r requirements.txt

# database to use
env: DJANGO_SETTINGS_MODULE=settings.travis

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script:
  - python manage.py test
