# Generated by Django 3.2.3 on 2021-06-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collective_decision', '0001_initial'),
        ('group', '0001_initial'),
        ('group_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('estimator', models.ManyToManyField(related_name='product_cost_estimation_of_members_in_group', through='collective_decision.Estimation', to='group_member.GroupMember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owns_product', to='group.group')),
                ('group_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_provider_of_product', to='group.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_in_group_tenant_of_product', to='group_member.groupmember')),
                ('user_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_in_group_provider_of_product', to='group_member.groupmember')),
            ],
        ),
    ]
