# Generated by Django 3.2.3 on 2021-06-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_members'),
        ('group_member', '0004_alter_groupmember_points_posseded'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_provider_of_product', to='group.group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_in_group_provider_of_product', to='group_member.groupmember'),
        ),
    ]
