# Generated by Django 3.2.3 on 2021-06-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_member', '0004_alter_groupmember_points_posseded'),
        ('product', '0002_auto_20210608_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_in_group_tenant_of_product', to='group_member.groupmember'),
        ),
    ]
