# Generated by Django 3.2.3 on 2021-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
