# Generated by Django 3.2.3 on 2021-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
