# Generated by Django 3.2.3 on 2021-07-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210722_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivered',
        ),
    ]
