# Generated by Django 3.2.5 on 2021-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
