# Generated by Django 3.2.3 on 2021-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collective_decision', '0002_initial'),
        ('group', '0001_initial'),
        ('group_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='decision_makers',
            field=models.ManyToManyField(related_name='vote_of_members_in_group', through='collective_decision.Decision', to='group_member.GroupMember'),
        ),
    ]
