# Generated by Django 3.2.3 on 2021-06-08 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_group_decision_makers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members_in_group', through='group_member.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
