# Generated by Django 3.2.3 on 2021-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
