# Generated by Django 3.2.3 on 2021-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
