# Generated by Django 3.2.3 on 2021-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
