# Generated by Django 3.2.3 on 2021-06-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('collective_decision', '0001_initial'),
        ('group_member', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_member.groupmember'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='decision',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='decision',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_member.groupmember'),
        ),
        migrations.AddConstraint(
            model_name='estimation',
            constraint=models.UniqueConstraint(fields=('group_member', 'product'), name='user_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.UniqueConstraint(fields=('group_member', 'group'), name='user_group_uniq'),
        ),
    ]
