# Generated by Django 3.2.3 on 2021-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_member', '0003_alter_groupmember_points_posseded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='points_posseded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
